/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 리프레시 토큰으로 액세스 토큰 재발급 */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/autofill': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** GPS/사진 기반 빈집 정보 자동입력 추천 */
    post: operations['ApplicationsController_autofill'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 신청 접수 (액세스 토큰 기반) */
    post: operations['ApplicationsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/documents/extract': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** PDF 서류 AI 자동입력 추출 (액세스 토큰 기반) */
    post: operations['ApplicationsController_extractDocuments'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 신청 목록 조회 (액세스 토큰 기반) */
    get: operations['ApplicationsController_myApplications'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/{id}/analysis': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 신청 건 AI 매물 분석 (액세스 토큰 기반) */
    get: operations['ApplicationsController_analyzeMyApplication'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/me/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 내 신청 건 상세 조회 (액세스 토큰 기반) */
    get: operations['ApplicationsController_myApplicationDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/verification/request-code': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 인증번호 요청 (조회/신청 공용) */
    post: operations['ApplicationsController_requestCode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/verification/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 신청용 인증번호 검증 */
    post: operations['ApplicationsController_verifySubmitCode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 신청 취소 (액세스 토큰 기반) */
    patch: operations['ApplicationsController_cancelMyApplication'];
    trace?: never;
  };
  '/api/v1/applications/admin/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 신청 현황 요약 */
    get: operations['ApplicationsController_adminSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/admin/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 신청 목록 조회 */
    get: operations['ApplicationsController_adminList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/admin/kanban': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 칸반 보드 조회 (파라미터 없음) */
    get: operations['ApplicationsController_adminKanban'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/admin/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 신청 상세 조회 */
    get: operations['ApplicationsController_adminDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 신청 상태 변경 (관리자) */
    patch: operations['ApplicationsController_updateStatus'];
    trace?: never;
  };
  '/api/v1/assets/listings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 매물 리스트 조회 (공공/개인 분리) */
    get: operations['AssetsController_listMarketplace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/assets/listings/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 매물 상세 조회 */
    get: operations['AssetsController_getListingDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AutofillHouseDto: {
      /** @example 제주특별자치도 제주시 한림읍 ... */
      address?: string;
      /** @example 33.4996 */
      latitude?: number;
      /** @example 126.5312 */
      longitude?: number;
      /**
       * @example STONE_WALL_HOUSE
       * @enum {string}
       */
      assetType?:
        | 'STONE_WALL_FIELD_HOUSE'
        | 'STONE_WALL_HOUSE'
        | 'DEMOLITION_HOUSE'
        | 'NO_STONE_WALL_HOUSE'
        | 'D_SHAPED_HOUSE'
        | 'URBAN_HOUSE_VILLA';
      /** @example 72 */
      areaSqm?: number;
      /**
       * @description 층수(단층=1)
       * @example 1
       */
      floorCount?: number;
      /**
       * @description 마당 유무
       * @example true
       */
      hasYard?: boolean;
      /**
       * @description 주차 가능 여부
       * @example true
       */
      hasParking?: boolean;
      /**
       * @example [
       *       "https://cdn.example.com/building-1.jpg"
       *     ]
       */
      photoUrls?: string[];
    };
    RequestVerificationDto: {
      /** @example 홍길동 */
      name: string;
      /** @example 010-1234-5678 */
      phone: string;
    };
    VerifyCodeDto: {
      /** @example 홍길동 */
      name: string;
      /** @example 010-1234-5678 */
      phone: string;
      /** @example 123456 */
      code: string;
    };
    UpdateStatusDto: {
      /**
       * @example REVIEWING
       * @enum {string}
       */
      status:
        | 'RECEIVED'
        | 'REVIEWING'
        | 'REMODELING'
        | 'LEASING'
        | 'COMPLETED'
        | 'REJECTED';
      /** @example 사업계획 보완 필요 */
      rejectReason?: string;
      /** @example 20대, 30대 */
      residentAgeGroup?: string;
      /** @example 카페 창업 */
      leasePurpose?: string;
      /** @example 2 */
      occupantCount?: number;
      /** @example 주방/전기 배선/화장실 리모델링 완료 */
      remodelSummary?: string;
      /** @example 제주시 건축과 064-000-0000 */
      managerContact?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 토큰 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_autofill: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AutofillHouseDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_create: {
    parameters: {
      query?: never;
      header: {
        'content-type': string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description 액세스 토큰 필수. JSON 또는 multipart/form-data 지원. multipart 사용 시 일반 필드는 그대로 넣고, 사진은 photos, 서류(PDF)는 documents 필드에 파일 첨부하세요. documents에 PDF가 포함되면 Gemini가 주소/건물유형/면적 등을 자동 추출합니다. */
    requestBody: {
      content: {
        'application/json': {
          /** @example owner@example.com */
          email?: string;
          /** @example 제주특별자치도 서귀포시 천지동 */
          address?: string;
          /** @example STONE_WALL_HOUSE */
          assetType?: string;
          /** @example 72 */
          areaSqm?: number;
          /** @example 1 */
          floorCount?: number;
          /** @example true */
          hasYard?: boolean;
          /** @example true */
          hasParking?: boolean;
          /** @example 건물 관련 추가 설명 */
          notes?: string;
          /**
           * @description 선택. multipart에서 JSON 문자열로 전달 가능. payload와 개별 필드가 겹치면 개별 필드 우선
           * @example {"address":"제주특별자치도 서귀포시 천지동","assetType":"STONE_WALL_HOUSE"}
           */
          payload?: string;
          photos?: string[];
          documents?: string[];
        };
        'multipart/form-data': {
          /** @example owner@example.com */
          email?: string;
          /** @example 제주특별자치도 서귀포시 천지동 */
          address?: string;
          /** @example STONE_WALL_HOUSE */
          assetType?: string;
          /** @example 72 */
          areaSqm?: number;
          /** @example 1 */
          floorCount?: number;
          /** @example true */
          hasYard?: boolean;
          /** @example true */
          hasParking?: boolean;
          /** @example 건물 관련 추가 설명 */
          notes?: string;
          /**
           * @description 선택. multipart에서 JSON 문자열로 전달 가능. payload와 개별 필드가 겹치면 개별 필드 우선
           * @example {"address":"제주특별자치도 서귀포시 천지동","assetType":"STONE_WALL_HOUSE"}
           */
          payload?: string;
          photos?: string[];
          documents?: string[];
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_extractDocuments: {
    parameters: {
      query?: never;
      header: {
        'content-type': string;
      };
      path?: never;
      cookie?: never;
    };
    /** @description multipart/form-data 권장. documents 필드에 PDF 파일을 첨부하면 Gemini가 문서를 읽어 자동입력 값을 추출합니다. */
    requestBody: {
      content: {
        'application/json': {
          documents?: string[];
        };
        'multipart/form-data': {
          documents?: string[];
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_myApplications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_analyzeMyApplication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_myApplicationDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_requestCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestVerificationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_verifySubmitCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyCodeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_cancelMyApplication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminSummary: {
    parameters: {
      query?: {
        /** @description YYYY-MM 형식 */
        month?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminList: {
    parameters: {
      query?: {
        status?:
          | 'RECEIVED'
          | 'REVIEWING'
          | 'REMODELING'
          | 'LEASING'
          | 'COMPLETED'
          | 'REJECTED';
        search?: string;
        sort?: 'latest' | 'oldest';
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminKanban: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_updateStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 신청서 ID (application.id) 또는 자산 ID (asset.id) */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateStatusDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  AssetsController_listMarketplace: {
    parameters: {
      query?: {
        /** @description 주소 키워드 검색 */
        address?: string;
        ownerCategory?: 'ALL' | 'PUBLIC' | 'PRIVATE';
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AssetsController_getListingDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
