/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 회원가입 */
    post: operations['AuthController_signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 로그인 */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 리프레시 토큰으로 액세스 토큰 재발급 */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 신청 접수 (회원가입 없이 이름/전화번호 기반) */
    post: operations['ApplicationsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/lookup/request-code': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 신청내역 조회용 인증번호 요청 */
    post: operations['ApplicationsController_requestLookupCode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/lookup/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 인증번호 검증 후 신청내역 조회 */
    post: operations['ApplicationsController_verifyAndLookup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/lookup/detail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 인증번호 검증 후 특정 신청 상세 조회 */
    post: operations['ApplicationsController_lookupDetail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 신청 취소 (전화번호 인증 기반) */
    patch: operations['ApplicationsController_cancel'];
    trace?: never;
  };
  '/api/v1/applications/admin/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 신청 현황 요약 */
    get: operations['ApplicationsController_adminSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/admin/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 신청 목록 조회 */
    get: operations['ApplicationsController_adminList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/admin/kanban': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 칸반 보드 조회 */
    get: operations['ApplicationsController_adminKanban'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/admin/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 관리자 신청 상세 조회 */
    get: operations['ApplicationsController_adminDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/applications/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 신청 상태 변경 (관리자) */
    patch: operations['ApplicationsController_updateStatus'];
    trace?: never;
  };
  '/api/v1/assets/listings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 매물 리스트 조회 (공공/개인 분리) */
    get: operations['AssetsController_listMarketplace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/assets/listings/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 매물 상세 조회 */
    get: operations['AssetsController_getListingDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/assets/{id}/inquiries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 개인 매물 임대 문의 접수 */
    post: operations['AssetsController_createInquiry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/files/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 신청용 파일 업로드 (회원가입 없이 사용 가능) */
    post: operations['FilesController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SignupDto: {
      /** @example youth@example.com */
      email: string;
      /**
       * @description 8~64자 영문/숫자/특수문자 조합
       * @example StrongPass123!
       */
      password: string;
      /** @example 홍길동 */
      name: string;
      /** @example 010-1234-5678 */
      phone?: string;
      /**
       * @example YOUTH
       * @enum {string}
       */
      role?: 'ELDER' | 'YOUTH' | 'ADMIN';
    };
    LoginDto: {
      /** @example youth@example.com */
      email: string;
      /** @example StrongPass123! */
      password: string;
    };
    ApplicationDocumentInputDto: {
      /** @example https://cdn.example.com/docs/registry.pdf */
      fileUrl: string;
      /**
       * @example PROPERTY_REGISTER
       * @enum {string}
       */
      type?:
        | 'PROPERTY_REGISTER'
        | 'BUILDING_REGISTER'
        | 'LAND_REGISTER'
        | 'FAMILY_RELATION_CERTIFICATE'
        | 'OTHER';
    };
    QuickApplicationDto: {
      /**
       * @description 신규 필드 (권장)
       * @example 홍길동
       */
      name?: string;
      /**
       * @description 하위 호환 필드
       * @example 홍길동
       */
      applicantName?: string;
      /**
       * @description 하이픈 포함 입력 허용
       * @example 010-1234-5678
       */
      phone: string;
      /** @example owner@example.com */
      email?: string;
      /**
       * @example EMPTY_HOUSE
       * @enum {string}
       */
      assetType?: 'EMPTY_HOUSE' | 'WAREHOUSE' | 'FIELD' | 'OTHER';
      /**
       * @example EMPTY_HOUSE
       * @enum {string}
       */
      detectedAssetType?: 'EMPTY_HOUSE' | 'WAREHOUSE' | 'FIELD' | 'OTHER';
      /** @example 제주특별자치도 제주시 한림읍 ... */
      address?: string;
      /** @example 제주특별자치도 제주시 한림읍 ... */
      detectedAddress?: string;
      /** @example 72 */
      areaSqm?: number;
      /** @example 72 */
      detectedAreaSqm?: number;
      /** @example 33.4996 */
      latitude?: number;
      /** @example 126.5312 */
      longitude?: number;
      /**
       * @example [
       *       "https://cdn.example.com/building-1.jpg"
       *     ]
       */
      photoUrls?: string[];
      /**
       * @description 레거시 문서 URL 리스트
       * @example [
       *       "https://cdn.example.com/registry.pdf"
       *     ]
       */
      documentUrls?: string[];
      /** @description 문서 유형 포함 문서 리스트 */
      documentFiles?: components['schemas']['ApplicationDocumentInputDto'][];
      /** @example 건물 관련 추가 설명 */
      notes?: string;
      /**
       * Format: uuid
       * @deprecated
       * @description 더 이상 사용하지 않습니다. 신청 시 빈집 자산은 항상 신규 생성됩니다.
       */
      assetId?: string;
      /**
       * Format: date
       * @example 2026-05-01
       */
      desiredStartDate?: string;
    };
    RequestVerificationDto: {
      /** @example 010-1234-5678 */
      phone: string;
    };
    VerifyCodeDto: {
      /** @example 010-1234-5678 */
      phone: string;
      /** @example 123456 */
      code: string;
    };
    LookupApplicationDetailDto: {
      /** Format: uuid */
      applicationId: string;
      /** @example 010-1234-5678 */
      phone: string;
      /** @example 123456 */
      code: string;
    };
    CancelApplicationDto: {
      /** @example 010-1234-5678 */
      phone: string;
      /** @example 123456 */
      code: string;
    };
    UpdateStatusDto: {
      /**
       * @example REVIEWING
       * @enum {string}
       */
      status:
        | 'RECEIVED'
        | 'REVIEWING'
        | 'REMODELING'
        | 'LEASING'
        | 'COMPLETED'
        | 'REJECTED';
      /** @example 사업계획 보완 필요 */
      rejectReason?: string;
      /** @example 20대, 30대 */
      residentAgeGroup?: string;
      /** @example 카페 창업 */
      leasePurpose?: string;
      /** @example 2 */
      occupantCount?: number;
      /** @example 주방/전기 배선/화장실 리모델링 완료 */
      remodelSummary?: string;
      /** @example 제주시 건축과 064-000-0000 */
      managerContact?: string;
    };
    CreateInquiryDto: {
      /** @example 홍길동 */
      name: string;
      /** @example 010-1234-5678 */
      phone: string;
      /** @example owner@example.com */
      email?: string;
      /** @example 게스트하우스 운영 */
      purpose: string;
      /** @example 가족 */
      householdType?: string;
      /** @example 2 */
      headCount?: number;
      /** @example 현장 확인 가능한 날짜를 안내 부탁드립니다. */
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupDto'];
      };
    };
    responses: {
      /** @description 회원가입 성공 (JWT 토큰 반환) */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      /** @description 로그인 성공 (JWT 토큰 반환) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 토큰 재발급 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuickApplicationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_requestLookupCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestVerificationDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_verifyAndLookup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyCodeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_lookupDetail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LookupApplicationDetailDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelApplicationDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminSummary: {
    parameters: {
      query?: {
        /** @description YYYY-MM 형식 */
        month?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminList: {
    parameters: {
      query?: {
        status?:
          | 'RECEIVED'
          | 'REVIEWING'
          | 'REMODELING'
          | 'LEASING'
          | 'COMPLETED'
          | 'REJECTED';
        search?: string;
        sort?: 'latest' | 'oldest';
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminKanban: {
    parameters: {
      query?: {
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_adminDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_updateStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateStatusDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AssetsController_listMarketplace: {
    parameters: {
      query?: {
        /** @description 주소 키워드 검색 */
        address?: string;
        ownerCategory?: 'ALL' | 'PUBLIC' | 'PRIVATE';
        page?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AssetsController_getListingDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AssetsController_createInquiry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateInquiryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilesController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
          name: string;
          phone: string;
          refType?: string;
          refId?: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
